version: "3.7"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23-alpine
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    volumes:
      - /mnt/pezzo/volumes/clickhouse/data:/var/lib/clickhouse
      - /mnt/pezzo/volumes/clickhouse/logs:/var/log/clickhouse-server
      - /mnt/pezzo/clickhouse/config/users.d/config.xml:/etc/clickhouse-server/users.d/config.xml
      - /mnt/pezzo/clickhouse/config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    healthcheck:
      test: ["CMD-SHELL", 'clickhouse-client --query "SELECT 1"']
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - pezzo-network

  pezzo-clickhouse-migrate:
    image: ghcr.io/pezzolabs/pezzo/server:latest
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    entrypoint: /bin/sh
    working_dir: /app/clickhouse
    command: -c "./migrate.sh"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    networks:
      - pezzo-network
    depends_on:
      - clickhouse

  pezzo-prisma-migrate:
    image: ghcr.io/pezzolabs/pezzo/server:latest
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    entrypoint: /bin/sh
    command: -c "npx prisma migrate deploy"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/pezzo
    networks:
      - pezzo-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pezzo_postgres_data:/var/lib/postgresql/data
    networks:
      - pezzo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  supertokens:
    image: supertokens/supertokens-postgresql:5.0
    ports:
      - "3567:3567"
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION_URI: postgres://postgres:postgres@postgres:5432/supertokens
    networks:
      - pezzo-network
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  redis-stack-server:
    image: redis/redis-stack-server:7.2.0-v0
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    networks:
      - pezzo-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  local-kms:
    image: nsmithuk/local-kms:latest
    container_name: local-kms
    entrypoint: "/bin/sh"
    # Seeding the local-kms with a master key. "/init/seed.yaml" will be created based on the base64 encoded string below.
    command: '-c "echo \"S2V5czoKICBTeW1tZXRyaWM6CiAgICBBZXM6CiAgICAgIC0gTWV0YWRhdGE6CiAgICAgICAgICBLZXlJZDogZGVtby1tYXN0ZXIta2V5CiAgICAgICAgQmFja2luZ0tleXM6CiAgICAgICAgICAtIDVjZGFlYWQyN2ZlN2RhMmRlNDc5NDVkNzNjZDZkNzllMzY0OTRlNzM4MDJmM2NkMzg2OWYxZDJjYjBiNWQ3YTkKCkFsaWFzZXM6CiAgLSBBbGlhc05hbWU6IGFsaWFzL3Rlc3RpbmcKICAgIFRhcmdldEtleUlkOiBkZW1vLW1hc3Rlci1rZXk=\" | base64 -d >> /init/seed.yaml && local-kms"'
    ports:
      - "9981:9981"
    expose:
      - "9981"
    environment:
      - "PORT=9981"
      - "KMS_REGION=us-east-1"
    networks:
      - pezzo-network

  pezzo-server:
    image: ghcr.io/pezzolabs/pezzo/server:latest
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/pezzo
      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - CLICKHOUSE_HOST=clickhouse
      - REDIS_URL=redis://redis-stack-server:6379
      - KMS_LOCAL_ENDPOINT=http://local-kms:9981
      - PINO_PRETTIFY=true
    networks:
      - traefik-public
      - pezzo-network
    ports:
      - "3000:3000"
    depends_on:
      - pezzo-prisma-migrate
      - pezzo-clickhouse-migrate
      - postgres
      - supertokens
      - clickhouse
      - redis-stack-server
    healthcheck:
      test: ["CMD-SHELL", "curl 'http://localhost:3000/api/healthz'"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.pezzo-server.rule=Host(`${PEZZO_SERVER_DOMAIN}`)
        - traefik.http.routers.pezzo-server.entrypoints=https
        - traefik.http.routers.pezzo-server.tls.certresolver=le
        - traefik.http.services.pezzo-server.loadbalancer.server.port=3000
        - traefik.http.services.pezzo-server.loadbalancer.passHostHeader=true
        - traefik.http.routers.pezzo-server.service=pezzo-server

  pezzo-console:
    image: ghcr.io/pezzolabs/pezzo/console:latest
    build:
      context: .
      dockerfile: ./apps/console/Dockerfile
    restart: always
    environment:
      - NX_BASE_API_URL="http://pezzo-server:3000"
      - NX_SUPERTOKENS_API_DOMAIN="http://pezzo-server:3000"
      - NX_SUPERTOKENS_WEBSITE_DOMAIN="http://pezzo-console:8080"
      - NX_DEBUG_MODE="true"
    networks:
      - traefik-public
      - pezzo-network
    ports:
      - "4200:8080"
    depends_on:
      - pezzo-server
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.pezzo-console.rule=Host(`${PEZZO_CONSOLE_DOMAIN}`)
        - traefik.http.routers.pezzo-console.entrypoints=https
        - traefik.http.routers.pezzo-console.tls.certresolver=le
        - traefik.http.services.pezzo-console.loadbalancer.server.port=4200
        - traefik.http.services.pezzo-console.loadbalancer.passHostHeader=true
        - traefik.http.routers.pezzo-console.service=pezzo-console

  pezzo-proxy:
    image: ghcr.io/pezzolabs/pezzo/proxy:latest
    build:
      context: .
      dockerfile: ./apps/proxy/Dockerfile
    restart: always
    networks:
      - traefik-public
      - pezzo-network
    ports:
      - "3001:3000"
    depends_on:
      - pezzo-server
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.pezzo-proxy.rule=Host(`${PEZZO_PROXY_DOMAIN}`)
        - traefik.http.routers.pezzo-proxy.entrypoints=https
        - traefik.http.routers.pezzo-proxy.tls.certresolver=le
        - traefik.http.services.pezzo-proxy.loadbalancer.server.port=3001
        - traefik.http.services.pezzo-proxy.loadbalancer.passHostHeader=true
        - traefik.http.routers.pezzo-proxy.service=pezzo-proxy

volumes:
  pezzo_postgres_data:
    external: true

networks:
  traefik-public:
    name: traefik-public
    external: true
  pezzo-network:
    name: pezzo-network
    external: false